version: "2"
services:
  postgres:
    container_name: class_postgres_2
    image: postgres:11.1
    restart: unless-stopped
    networks:
      - my-net
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "myuser-pw!"
      POSTGRES_DB: "gogs"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "gogs"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
     - "../../../postgres/data/data:/var/lib/postgresql/data"
  gogs:
    container_name: class_gogs_2
    image: gogs/gogs:0.11.66
    restart: unless-stopped
    networks:
      - my-net
    depends_on:
      # https://docs.docker.com/compose/compose-file/compose-file-v2/#depends_on
      # https://docs.docker.com/compose/compose-file/compose-file-v2/#healthcheck
      - postgres
    ports:
      - "10022:22"
      - "10080:3000"
    volumes:
     - "../../../gogs/data:/data"
     - "../../../gogs/logs:/app/gogs/log"
networks:
  my-net:
    driver: bridge
